language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    -
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew


before_deploy:
  - zip -r Ex_Springboot-AWS *
  - mkdir -p deploy
  - mv Ex_Springboot-AWS.zip deploy/Ex_Springboot-AWS.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo setting 에 설정된 값
    bucket: ex-springboot-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값

    bucket: ex-springboot-build #S3버킷
    key: Ex_Springboot-AWS.zip # 빌드 파일을 압축해서 전달

    bundle_type: zip # 압축 확장자
    application: Ex_Springboot-AWS

    deployment_group: Ex_Springboot-AWS-group

    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람 .
notifications:
  email:
    recipients:
      - njg7194@naver.com
